version: '3.8'

services:
  api:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app/
    env_file:
      - .env
    depends_on:
      - db
    command: uvicorn app.main:create_app --factory --host 0.0.0.0 --port 8000 --reload

  db:
    image: postgres:15-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    env_file:
      - .env

volumes:
  postgres_data:
    # This named volume ensures that the database data is persisted
    # across container restarts.
    name: azure-emulator-postgres-data
