"""
SQLModel definitions for database tables.

This module contains the class definitions for all database models, which
SQLModel uses to interact with the database tables.
"""
from typing import Optional
from sqlmodel import Field, SQLModel

class VirtualMachine(SQLModel, table=True):
    """
    Represents a virtual machine resource in the database.
    """
    # The primary key for the table, automatically generated by the database.
    id: Optional[int] = Field(default=None, primary_key=True)

    # The name of the virtual machine. It is indexed for faster lookups.
    name: str = Field(index=True)

    # The name of the resource group the VM belongs to. Also indexed.
    resource_group: str = Field(index=True)

    # The Azure region where the VM is located.
    location: str

    # The size of the virtual machine (e.g., "Standard_D2s_v3").
    vm_size: str

    # The provisioning state of the resource (e.g., "Succeeded", "Failed").
    provisioning_state: str = "Succeeded"
